In [6]:
import pandas as pd

train_df = pd.read_csv('train.csv')
print(train_df.shape)
train_df.head()

(9741, 3)

,answerKey,question,choices
0,A,The sanctions against the school were a punish...,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
1,B,Sammy wanted to go to where the people were. ...,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
2,A,To locate a choker not located in a jewelry bo...,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
3,D,Google Maps and other highway and street GPS s...,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
4,C,"The fox walked from the city into the forest, ...","{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."

In [7]:
test_df = pd.read_csv('test.csv')
print(test_df.shape)
test_df.head()

(1140, 3)

,answerKey,question,choices
0,NaN,"The townhouse was a hard sell for the realtor,...","{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
1,NaN,There is a star at the center of what group of...,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
2,NaN,What were the kids doing as they looked up at ...,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
3,NaN,The person taught an advanced class only for who?,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
4,NaN,What is a likely consequence of ignorance of r...,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."

In [8]:
val_df = pd.read_csv('validation.csv')
print(val_df.shape)
val_df.head()

(1221, 3)

,answerKey,question,choices
0,A,A revolving door is convenient for two directi...,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
1,A,What do people aim to do at work?,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
2,B,Where would you find magazines along side many...,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
3,A,Where are you likely to find a hamburger?,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."
4,A,James was looking for a good place to buy farm...,"{'label': array(['A', 'B', 'C', 'D', 'E'], dty..."